### PR TITLE
Fix bendin

### PR DESCRIPTION
**Pull request by agraef**
Here's the last one, with the improved bendin object and -legacy-bendin option, as promised.

### CODE REVIEW

**Comment by agraef** [comment]
I'm just going to merge this now, since you already said that you want it, I've tested that it works the same way as in purr-data, and I can then go on and update my pd-l2ork packages on the OBS once more and be done with it.

**Comment by pd-l2ork** [comment]
Excellent, thank you, Albert. Is there anything missing from the previous or this commit, or is this it for the time being?

**Comment by agraef** [comment]
This is it. I already updated my packages on the OBS again, they built fine.

**Comment by pd-l2ork** [comment]
Excellent, thank you, Albert.

**Pull request merged**
