### PR TITLE
Gem update

### PR DESCRIPTION
**Pull request by agraef**
While I'm at it, I also updated the Gem submodule to the latest source from the mirror, so that it's in sync with purr-data again. Please note that this PR builds on #60, so that PR needs to be merged first.

### CODE REVIEW

**Comment by pd-l2ork** [comment]
Excellent, thank you, Albert. I have merged the request. Is it safe to assume that the wiring pi module is set to be on the snapshot that the original code did a hard reset to? This is important because that's to the best of my knowledge the last stable release that allowed for static linking.

**Comment by pd-l2ork** [comment]
Ugh, just saw you referencing #60. Did I merge this correctly? By the looks of it, it seems like all 3 commits were merged. Also, did you also create merge request for the bendin?

**Comment by agraef** [comment]
No, but never mind, the end result is about the same.

**Comment by pd-l2ork** [comment]
So, to confirm, is the wiring pi snapshot on the right version to allow for static library creation and do you have the bend in merge request, as well?

**Comment by agraef** [comment]
1. Yes, it's exactly the same revision that was being used before, rev. 96344ff7. 2. Yes, see #62.

**Pull request merged**
